# Generated by Django 3.2.7 on 2023-08-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesas',
            name='link',
        ),
    ]
