# Generated by Django 3.2.7 on 2023-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_hamburguesas_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesas',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion Web'),
        ),
    ]
