# Generated by Django 3.2.7 on 2023-08-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_hamburguesas_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesas',
            name='link',
        ),
    ]
